//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AG.COM.SDM.Utility {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonVariablesKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonVariablesKeys() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AG.COM.SDM.Utility.CommonVariablesKeys", typeof(CommonVariablesKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 DataBaseType 的本地化字符串。
        /// </summary>
        public static string DataBaseType {
            get {
                return ResourceManager.GetString("DataBaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OLEConnColl 的本地化字符串。
        /// </summary>
        public static string OLEConnColl {
            get {
                return ResourceManager.GetString("OLEConnColl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OLEDataBase 的本地化字符串。
        /// </summary>
        public static string OLEDataBase {
            get {
                return ResourceManager.GetString("OLEDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OLEPassword 的本地化字符串。
        /// </summary>
        public static string OLEPassword {
            get {
                return ResourceManager.GetString("OLEPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OLEPort 的本地化字符串。
        /// </summary>
        public static string OLEPort {
            get {
                return ResourceManager.GetString("OLEPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OLEServer 的本地化字符串。
        /// </summary>
        public static string OLEServer {
            get {
                return ResourceManager.GetString("OLEServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OLEUser 的本地化字符串。
        /// </summary>
        public static string OLEUser {
            get {
                return ResourceManager.GetString("OLEUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDEDatabase 的本地化字符串。
        /// </summary>
        public static string SDEDatabase {
            get {
                return ResourceManager.GetString("SDEDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDEDBType 的本地化字符串。
        /// </summary>
        public static string SDEDBType {
            get {
                return ResourceManager.GetString("SDEDBType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDEInstance 的本地化字符串。
        /// </summary>
        public static string SDEInstance {
            get {
                return ResourceManager.GetString("SDEInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDEPassword 的本地化字符串。
        /// </summary>
        public static string SDEPassword {
            get {
                return ResourceManager.GetString("SDEPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDEServer 的本地化字符串。
        /// </summary>
        public static string SDEServer {
            get {
                return ResourceManager.GetString("SDEServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDEUser 的本地化字符串。
        /// </summary>
        public static string SDEUser {
            get {
                return ResourceManager.GetString("SDEUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SDEVersion 的本地化字符串。
        /// </summary>
        public static string SDEVersion {
            get {
                return ResourceManager.GetString("SDEVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SketchSymbol 的本地化字符串。
        /// </summary>
        public static string SketchSymbol {
            get {
                return ResourceManager.GetString("SketchSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SnapSymbol_Centroid 的本地化字符串。
        /// </summary>
        public static string SnapSymbol_Centroid {
            get {
                return ResourceManager.GetString("SnapSymbol_Centroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SnapSymbol_Edge 的本地化字符串。
        /// </summary>
        public static string SnapSymbol_Edge {
            get {
                return ResourceManager.GetString("SnapSymbol_Edge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SnapSymbol_Endpoint 的本地化字符串。
        /// </summary>
        public static string SnapSymbol_Endpoint {
            get {
                return ResourceManager.GetString("SnapSymbol_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SnapSymbol_PerpendicularFoot 的本地化字符串。
        /// </summary>
        public static string SnapSymbol_PerpendicularFoot {
            get {
                return ResourceManager.GetString("SnapSymbol_PerpendicularFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SnapSymbol_Vertex 的本地化字符串。
        /// </summary>
        public static string SnapSymbol_Vertex {
            get {
                return ResourceManager.GetString("SnapSymbol_Vertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StyleFiles 的本地化字符串。
        /// </summary>
        public static string StyleFiles {
            get {
                return ResourceManager.GetString("StyleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AM_LOGGER 的本地化字符串。
        /// </summary>
        public static string SYSLogger {
            get {
                return ResourceManager.GetString("SYSLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AM_SYSTEM_MainMenu 的本地化字符串。
        /// </summary>
        public static string SYSMainMenu {
            get {
                return ResourceManager.GetString("SYSMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AM_SYSTEM_STARTITEM 的本地化字符串。
        /// </summary>
        public static string SYSStartItem {
            get {
                return ResourceManager.GetString("SYSStartItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AM_SYSTEM_User 的本地化字符串。
        /// </summary>
        public static string SYSUser {
            get {
                return ResourceManager.GetString("SYSUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UIDesignLoadFrom 的本地化字符串。
        /// </summary>
        public static string UIDesignLoadFrom {
            get {
                return ResourceManager.GetString("UIDesignLoadFrom", resourceCulture);
            }
        }
    }
}
